### PR TITLE
Revert "Revert "add check-commit-signing action""

### PR DESCRIPTION
**Pull request by altendky**
This action goes out of it's way to simply check if the commits are signed at all without verifying any of the signatures.  If, or when, signature checks are wanted there may be interest in https://github.com/frankywahl/allowedSignersFile or similar to collect ssh keys from GitHub to check against.

Reverts Chia-Network/actions#66

https://github.com/Chia-Network/actions/actions/runs/3599290314/jobs/6062780993#step:3:45
> `error: gpg.ssh.allowedSignersFile needs to be configured and exist for ssh signature verification`

Draft for:
- [x] testing with an ssh signed commit
- [x] making it work with an ssh signed commit

### CODE REVIEW

**Comment by altendky** [comment]
image

**Review by cmmarslender — APPROVED** [review]

**Comment by altendky** [comment]
holding for a moment, i see two failed ci notifications and i'm not sure what's up

**Comment by altendky** [comment]
Env creation and activation were broken.  Those changes have been reverted and are being recovered in https://github.com/Chia-Network/actions/pull/76.

**Review by wallentx — APPROVED** [review]
LGTM

**Pull request merged**
